version: "3.3" 

# TODO: Add a Service for the Frontend <- This would just make deployments easier in the future
services:
  natl_backend_api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - deployment=compose
    depends_on:
      - db
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=developer
  frontend:
    build:
      context: ./natl-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  test:
    build:
      context: ./tests
      dockerfile: Dockerfile
    environment:
      - api_url=http://natl_backend_api:8081/api
    depends_on:
      - db
      - natl_backend_api