name: Docker multi-container stack test and deploy.

on:
  pull_request:
    branches: [main, develop]

jobs:
  docker-compose test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build images with docker-compose
        run: docker-compose build
