name: Docker multi-container stack testing.

on:
  pull_request:
    branches: [main, develop]

jobs:
  docker-compose:
    name: Test docker-compose build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build app Docker images with docker-compose
        run: docker-compose build

  python_linter:
    name: Python linting check
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend/src
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U flake8
          flake8 --max-line-length=120
        working-directory: ${{ env.working-directory}}

  hadolint-linter:
    name: Dockerfile linting check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Lint backend dockerfile
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: ./backend/Dockerfile
      - name: Lint SQL dockerfile
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: ./mysql/Dockerfile
      - name: Lint frontend dockerfile
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: ./natl-frontend/Dockerfile
      - name: Lint test dockerfile
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: ./tests/Dockerfile

  sql-linter:
    name: SQL linting check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Execute sql linter
        run: |
          node --version
          npm i -g sql-lint
          sql-lint mysql/1_create_database.sql
          sql-lint mysql/2_create_test_data.sql

  unit-tests:
    name: Unit test check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: |
          docker-compose build --parallel
          docker-compose up -d natl_backend_api db
          docker compose run --rm test
          exit $?
